version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge

  app:
    build:
      context: app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: ["bash", "run.sh"]
    networks:
      - challenge
    volumes:
      - ./app:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - challenge
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - app

networks:
  challenge:
    driver: bridge